
package dcc.com.agent.message.oxm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubscriptionPortService", targetNamespace = "http://krams915.blogspot.com/ws/schema/oss", wsdlLocation = "http://localhost:8080/spring-ws-si/krams/ws/subscription.wsdl")
public class SubscriptionPortService
    extends Service
{

    private final static URL SUBSCRIPTIONPORTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/spring-ws-si/krams/ws/subscription.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SUBSCRIPTIONPORTSERVICE_WSDL_LOCATION = url;
    }

    public SubscriptionPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionPortService() {
        super(SUBSCRIPTIONPORTSERVICE_WSDL_LOCATION, new QName("http://krams915.blogspot.com/ws/schema/oss", "SubscriptionPortService"));
    }

    /**
     * 
     * @return
     *     returns SubscriptionPort
     */
    @WebEndpoint(name = "SubscriptionPortSoap11")
    public SubscriptionPort getSubscriptionPortSoap11() {
        return super.getPort(new QName("http://krams915.blogspot.com/ws/schema/oss", "SubscriptionPortSoap11"), SubscriptionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionPort
     */
    @WebEndpoint(name = "SubscriptionPortSoap11")
    public SubscriptionPort getSubscriptionPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://krams915.blogspot.com/ws/schema/oss", "SubscriptionPortSoap11"), SubscriptionPort.class, features);
    }

}
